# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.19.0
import pydantic
from typing import Optional


class User(pydantic.BaseModel):
    id: int
    name: Optional[str]
    email: Optional[str]
